version: "3"
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_proxy
    restart: always
    tty: true
    volumes:
      - ./backend-not-found.html:/var/www/html/backend-not-found.html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./includes:/etc/nginx/includes
    ports:
      - 80:80
    networks:
      - app

networks:
  app:
    external:
      name: network_sis
