version: "3"
services:
  proxy:
    container_name: nginx_proxy
    restart: always
    build: ./
    ports:
      - 80:80
    volumes:
      - ./:/usr/app
    networks:
      - app

networks:
  app:
    external:
      name: network_sis
