version: "3"
services:
  proxy:
    build: ./
    ports:
      - 80:80
    networks:
      - app
    command: [nginx-debug, '-g', 'daemon off;']

networks:
  app:
    external:
      name: network_sis
