version: "3"
services:
  app:
    image: nginx:1.12
    volumes:
      - .:/usr/share/nginx/html/
    expose:
      - "80"
    networks:
      - app

networks:
  app:
    external:
      name: network_sis
